# Create a deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiap-registro
spec:
  selector:
    matchLabels:
      app: fiap-registro
  replicas: 1
  template:
    metadata:
#      annotations:
#        eks.amazonaws.com/role-arn: arn:aws:iam::231670762225:role/my-app-service-account
      labels:
        app: fiap-registro
    spec:
      containers:
        - name: fiap-registro
          image: plobon/fiap-registro:v1
          imagePullPolicy: "Always"
          env:
            - name: spring.application.name
              valueFrom: 
                configMapKeyRef:
                  name: fiap-registro-config
                  key: spring_application_name
            - name: server.servlet.context-path
              valueFrom:
                configMapKeyRef:
                  name: fiap-registro-config
                  key: server_servlet_context_path
            - name: jwt.expiration
              valueFrom:
                configMapKeyRef:
                  name: fiap-registro-config
                  key: jwt_expiration
            - name: server.port
              valueFrom:
                configMapKeyRef:
                  name: fiap-registro-config
                  key: server_port
            - name: spring.jpa.properties.hibernate.dialect
              valueFrom:
                configMapKeyRef:
                  name: fiap-registro-config
                  key: spring_jpa_properties_hibernate_dialect
            - name: spring.datasource.initialization-mode
              valueFrom:
                configMapKeyRef:
                  name: fiap-registro-config
                  key: spring_datasource_initialization-mode
            - name: spring.datasource.initialize
              valueFrom:
                configMapKeyRef:
                  name: fiap-registro-config
                  key: spring_datasource_initialize
            - name: spring.jpa.hibernate.show-sql
              valueFrom:
                configMapKeyRef:
                  name: fiap-registro-config
                  key: spring_jpa_hibernate_show-sql
            - name: spring.jpa.hibernate.ddl-auto
              valueFrom:
                configMapKeyRef:
                  name: fiap-registro-config
                  key: spring_jpa_hibernate_ddl-auto
            - name: jwt.secret
              valueFrom:
                configMapKeyRef:
                  name: fiap-registro-config
                  key: jwt_secret
            - name: queue.atualiza.registro.ponto
              valueFrom:
                configMapKeyRef:
                  name: fiap-registro-config
                  key: queue

          ports:
            - containerPort: 9092

